#
# Copyright 2010-2014 Fabric Software Inc. All rights reserved.
#
import platform, json, os, shutil
Import('parentEnv', 'kl2edk', 'kl', 'extSuffix', 'STAGE_DIR')

extName = 'XBox'

env = parentEnv.Clone()
env.Append(CPPPATH = [env.Dir('.').abspath])
env.Append(CPPPATH = [env.Dir('thirdparty').abspath])
env.Append(LIBS = ['libboost_thread-vc100-mt-s-1_55'])
env.Append(CCFLAGS = ['/EHsc'])

if platform.system().lower().startswith('win'):
  env.Append(LIBS = ['xinput'])
elif platform.system().lower().startswith('lin'):
  env.Append(LIBS = ['udev'])

# env.Append(LIBS = [
#   'ws2_32.lib',
#   'opengl32.lib',
#   'Dbghelp.lib',
#   'winmm.lib',
#   'kernel32.lib',
#   'user32.lib',
#   'gdi32.lib',
#   'winspool.lib',
#   'comdlg32.lib',
#   'advapi32.lib',
#   'shell32.lib',
#   'ole32.lib',
#   'oleaut32.lib',
#   'uuid.lib',
#   'odbc32.lib',
#   'odbccp32.lib'
# ])

sources = [
  env.File(extName+'.fpm.json')
]
sources += env.Glob('*.kl')

cppFiles = [
  env.File('XBoxController_functions.cpp'),
  env.Dir('thirdparty').File('gamepad.c')
]

headers = [
  env.File('XBox.h')
]

extData = json.loads(open(sources[0].srcnode().abspath, 'r').read())
extVersion = extData['version']

extStageDir = STAGE_DIR.Dir('Exts').Dir(extName)
presetStageDir = STAGE_DIR.Dir('Presets').Dir('DFG').Dir('ThirdParty').Dir(extName)
extensionFiles = env.Install(extStageDir, [env.File(extName+'.fpm.json')] + env.Glob('*.kl'))
kl2dfgLogFile = presetStageDir.File('kl2dfg.log')
kl2edkResults = env.RunKL2EDK(headers, sources)
kl2dfgResults = env.RunKL2DFG([kl2dfgLogFile], extensionFiles)

extLibFileName = env.File(extName + '-' + extSuffix)
libraryFiles = Flatten([env.SharedLibrary(extLibFileName, cppFiles)])
env.Depends(cppFiles, kl2edkResults)
env.Depends(kl2dfgResults, kl2edkResults + libraryFiles)

extensionFiles += env.Install(extStageDir, libraryFiles[0])
extensionFiles += kl2edkResults
extensionFiles += kl2dfgResults
extensionFiles = Flatten(extensionFiles)

env.AlwaysBuild(extensionFiles)
alias = env.Alias(extName, extensionFiles)

Return('alias')
